name: Tiny Art Generator

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */8 * * *" # every 8 hours
  workflow_dispatch: # allow manual runs

jobs:
  generate-art:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # we push with PAT instead

      - name: Generate ASCII art partial
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p app/views/shared
          ART=""
          CHARS='*<^°>'
          for i in {1..20}; do
            ROW=""
            for j in {1..20}; do
              if [ "$i" -eq 1 ] || [ "$i" -eq 20 ] || [ "$j" -eq 1 ] || [ "$j" -eq 20 ]; then
                ROW="${ROW}*"            # border
              elif [ "$i" -eq "$j" ] || [ $(( i + j - 1 )) -eq 20 ]; then
                ROW="${ROW}^"            # diagonal/X
              else
                idx=$(( RANDOM % ${#CHARS} ))
                ROW="${ROW}${CHARS:idx:1}"
              fi
            done
            ART="${ART}${ROW}\n"
          done
          printf '<pre>%b</pre>\n' "$ART" > app/views/shared/_tiny_art.html.erb

      - name: Commit and push
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.PERSONAL_TOKEN }} # you need to create this PAT secret
          GIT_AUTHOR_NAME: "Sonia Chaboud"
          GIT_AUTHOR_EMAIL: "123456+Sonickaa@users.noreply.github.com" # replace with your real noreply
          GIT_COMMITTER_NAME: "Sonia Chaboud"
          GIT_COMMITTER_EMAIL: "123456+Sonickaa@users.noreply.github.com"
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git add app/views/shared/_tiny_art.html.erb
          git commit -m "Generate new tiny ASCII art $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${REPO}
          git push origin HEAD:main
