name: Tiny Art Generator

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */8 * * *" # every 8 hours
  workflow_dispatch: # allow manual runs

jobs:
  generate-art:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Generate ASCII art partial
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p app/views/shared
          ART=""
          CHARS='*<^°>'
          ROWS=20
          COLS=20
          for i in $(seq 1 $ROWS); do
            ROW=""
            for j in $(seq 1 $COLS); do
              if [ "$i" -eq 1 ] || [ "$i" -eq "$ROWS" ] || [ "$j" -eq 1 ] || [ "$j" -eq "$COLS" ]; then
                ROW="${ROW}*"
              elif [ "$i" -eq "$j" ] || [ $(( i + j - 1 )) -eq "$ROWS" ]; then
                ROW="${ROW}^"
              else
                idx=$(( RANDOM % ${#CHARS} ))
                ROW="${ROW}${CHARS:idx:1}"
              fi
            done
            ART="${ART}${ROW}\n"
          done
          printf '<pre>%b</pre>\n' "$ART" > app/views/shared/_tiny_art.html.erb

      - name: Commit & push (as you)
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GIT_AUTHOR_NAME: "Sonia Chaboud"
          GIT_AUTHOR_EMAIL: "122700687+Sonickaa@users.noreply.github.com" # <-- replace this
          GIT_COMMITTER_NAME: "Sonia Chaboud"
          GIT_COMMITTER_EMAIL: "122700687+Sonickaa@users.noreply.github.com" # <-- replace this
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git add app/views/shared/_tiny_art.html.erb
          git commit -m "Generate new tiny ASCII art $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || { echo "No changes to commit"; exit 0; }
          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${REPO}.git"
          git push origin HEAD:main
