name: Tiny Art Generator

on:
  schedule:
    - cron: "0 */8 * * *" # every 8 hours
  workflow_dispatch: # allows manual run

jobs:
  generate-art:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣
      - run: |
          mkdir -p app/views/shared
          ART=""
          CHARS="*<^°>"
          for i in {1..20}; do
            ROW=""
            for j in {1..20}; do
              if [ $i -eq 1 ] || [ $i -eq 20 ] || [ $j -eq 1 ] || [ $j -eq 20 ]; then
                ROW="$ROW*"  # border
              elif [ $i -eq $j ] || [ $i + $j - 1 -eq 20 ]; then
                ROW="$ROW^"  # diagonal
              else
                ROW="$ROW${CHARS:RANDOM%5:1}"  # random inside
              fi
            done
            ART="$ART$ROW\n"
          done
          echo -e "<pre>$ART</pre>" > app/views/shared/_tiny_art.html.erb

      # 3️⃣ Commit and push changes
- run: |
    git config user.name "Sonia Chaboud"
    git config user.email "your-email@example.com"
    git add app/views/shared/_tiny_art.html.erb
    git commit -m "Generate new tiny ASCII art $(date)" || echo "No changes to commit"
    git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
